/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/dashboard:
  controller: Dash
  action: dash
  
/calculatrice_materiaux:
  controller: Materiaux
  action: calculatrice

/backoffice:
  controller: Back
  action: home

/generate_devis_pdf:
  controller: Devis
  action: generatePDF

/formulaire_devis:
  controller: Devis
  action: showForm

/submit_devis:
  controller: Devis
  action: submitDevis

/forgot_password:
  controller: Password
  action: forgot

/reset_password:
  controller: Password
  action: reset

/mail:
  controller: Mail
  action: sendMail