/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register


/preview-quote:
  controller: Devis
  action: devis_preview

/generate-quote-pdf:
  controller: Devis
  action: devis_preview

/dashboard:
  controller: Dash
  action: dash
  
/calculatrice_materiaux:
  controller: Materiaux
  action: calculatrice

/backoffice:
  controller: Back
  action: home
