/:
  controller: Main
  action: home

/a-propos:
  controller: Main
  action: aboutUs

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/preview-quote:
  controller: Devis
  action: devis_preview

# Gardez votre route actuelle pour la génération du PDF
/generate-quote-pdf:
  controller: Devis
  action: devis_preview